apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole-v4.3.2-1-deployment
  labels:
    app: pihole-v4.3.2-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole-v4.3.2-1

  template:
    metadata:
      labels:
        app: pihole-v4.3.2-1
    spec:

      volumes:
      - name: pihole-v4-3-2-1-data-etc-pihole
        flexVolume:
          driver: "fstab/cifs"
          fsType: "cifs"
          secretRef:
            name: "network-storage-cifs-secret"
          options:
            networkPath: "//<server>/storage/pihole-v4-3-2-1/pihole"
            mountOptions: "vers=1.0"

      - name: pihole-v4-3-2-1-data-etc-dnsmasqd
        flexVolume:
          driver: "fstab/cifs"
          fsType: "cifs"
          secretRef:
            name: "network-storage-cifs-secret"
          options:
            networkPath: "//<server>/storage/pihole-v4-3-2-1/dnsmasq.d"
            mountOptions: "vers=1.0"

      containers:
      - name: pihole-v4-3-2-1-container
        image: pihole/pihole:4.3.2-1_armhf
        imagePullPolicy: IfNotPresent

        ports:
          - containerPort: 53
            name: dns-tcp
            protocol: TCP
          - containerPort: 53
            name: dns-udp
            protocol: UDP
          - containerPort: 67
            name: dhcp-udp
            protocol: UDP
          - containerPort: 80
            name: http-tcp
            protocol: TCP
          - containerPort: 443
            name: https-tcp
            protocol: TCP

        volumeMounts:
          - name: pihole-v4-3-2-1-data-etc-pihole
            mountPath: /etc/pihole
          - name: pihole-v4-3-2-1-data-etc-dnsmasqd
            mountPath: /etc/dnsmasq.d

        env:
          - name: DNS1
            value: "8.8.8.8"
          - name: DNS2
            value: "208.67.222.222"
          - name: ServerIP
            value: <IP address assigned to Load Balancer>
          - name: TZ
            value: "America/Los_Angeles"
          - name: WEBPASSWORD
            valueFrom:
              secretKeyRef:
                name: pihole-ui-secret
                key: password

  restartPolicy: Always