apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ .Chart.Version }}-deployment
  labels:
    app: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-{{ .Chart.Version }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-{{ .Chart.Version }}
      annotations:
        config-checksum: {{ .Values.dns.custom | print | sha256sum }}

    spec:

      volumes:
      - name: {{ .Chart.Name }}-{{ .Chart.AppVersion }}-data-etc-pihole
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}-{{ .Chart.AppVersion }}-pihole-root-pvclaim

      - name: config-volume
        configMap:
          name: {{ .Values.config.name }}

      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          {{- if .Values.dhcp.server }}
          - {{ .Values.dhcp.server }}
          {{- end }}
          {{- range .Values.container.nameservers }}
          - {{ . }}
          {{- end }}

      containers:
        - name: {{ .Chart.Name }}-{{ .Chart.AppVersion }}-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: dns-tcp
              containerPort: {{ .Values.service.dns.port }}
              protocol: TCP

            - name: dns-udp
              containerPort: {{ .Values.service.dns.port }}
              protocol: UDP

            - name: dhcp-udp
              containerPort: {{ .Values.service.dhcp.port }}
              protocol: UDP

            - name: http-tcp
              containerPort: {{ .Values.service.http.port }}
              protocol: TCP

            - name: https-tcp
              containerPort: {{ .Values.service.https.port }}
              protocol: TCP

          volumeMounts:
            - name: {{ .Chart.Name }}-{{ .Chart.AppVersion }}-data-etc-pihole
              mountPath: /etc/pihole
            - name: config-volume
              mountPath: /etc/pihole/pihole-FTL.conf
              subPath: pihole-FTL.conf
            - name: config-volume
              mountPath: /etc/dnsmasq.d/custom-dns.conf
              subPath: custom-dns.conf

          env:
            - name: DNS1
              value: {{ .Values.dns._1 }}
            - name: DNS2
              value: {{ .Values.dns._2 }}
            - name: ServerIP
              value: {{ .Values.service.ip }}
            - name: TZ
              value: {{ .Values.timezone }}
            - name: WEBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.ui.name }}
                  key: password

          # livenessProbe:
          #   exec:
          #     command:
          #       - nslookup
          #       - -timeout=2
          #       - google.com
          #       - {{ .Values.service.ip }}
          #   initialDelaySeconds: 60
          #   periodSeconds: 30
            # httpGet:
            #   path: /
            #   port: http-tcp
            # initialDelaySeconds: 60
            # periodSeconds: 30

          livenessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5

          readinessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 10

      {{- if .Values.affinity.value }}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: {{ .Values.affinity.weight }}
              preference:
                matchExpressions:
                  - key: "{{ .Values.affinity.label }}"
                    operator: In
                    values: 
                      {{- range .Values.affinity.value }}
                      - {{ . | quote }}
                      {{- end }}
      {{- end }}