apiVersion: v1
kind: Service

metadata:
  name: {{ .Chart.Name }}-{{ .Chart.AppVersion }}-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ .Chart.Name }}-{{ .Chart.Version }}
  labels:
    app: {{ .Chart.Name }}-{{ .Chart.Version }}

spec:
  selector:
    app: {{ .Chart.Name }}-{{ .Chart.Version }}

  type: {{ .Values.service.type }}
  externalTrafficPolicy: Local
  loadBalancerIP: {{ .Values.service.ip }}

  ports:
    - name: http
      port: {{ .Values.service.http.port }}
      targetPort: http-tcp
      protocol: TCP

    - name: https
      port: {{ .Values.service.https.port }}
      targetPort: https-tcp
      protocol: TCP

    - name: dns
      port: {{ .Values.service.dns.port }}
      targetPort: dns-tcp
      protocol: TCP