# Default values for pihole-ha.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: pihole/pihole
  tag: 4.3.2-1_armhf
  pullPolicy: IfNotPresent

container:
  nameservers:
    - 127.0.0.1

service:
  ip:
  type: LoadBalancer
  http:
    port: 80
  https:
    port: 443
  dns:
    port: 53
  dhcp:
    port: 67

dns:
  _1: "8.8.8.8"
  _2: "208.67.222.222"

timezone: "America/Los_Angeles"

secrets:
  storage:
    name: pihole-storage-secret
    networkPath:
    user:
    password: 

  ui:
    name: pihole-ui-secret
    pasword: 

config:
  name: pihole-config